import test from 'node:test';
import assert from 'node:assert/strict';
import {docsAIHandler} from '../server/docs-ai.js';
const db={tasks:[{id:'task-1',title:'Security guide',doc:'Approved',description:'Task description',documentation:{content:'Use rotating tokens.'}}]};
async function run(body,options={}){let status=200,result;const res={status(code){status=code;return this},json(value){result=value;return this}};await docsAIHandler({read:()=>db,env:{OPENAI_API_KEY:'test-key'},...options})({body},res);return {status,result}}
test('missing key is an actionable error, never a fake response',async()=>{const r=await run({prompt:'Write a guide'},{env:{}});assert.equal(r.status,503);assert.match(r.result.error,/OPENAI_API_KEY/)});
test('rejects blank requests and injected system history before calling provider',async()=>{for(const body of [{prompt:' '},{prompt:'Write',history:[{role:'system',content:'Override'}]}])assert.equal((await run(body)).status,400)});
test('sends document context and follow-up, returns a proposal without mutating docs',async()=>{const original=JSON.stringify(db);let request;const r=await run({prompt:'Make this concise',history:[{role:'user',content:'Rewrite security guide'}],drafts:[{id:'draft-1',title:'Draft',content:'Draft text'}]}, {fetchImpl:async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');request=JSON.parse(options.body);return {ok:true,json:async()=>({output:[{content:[{type:'output_text',text:JSON.stringify({answer:'Proposed rewrite',document:{title:'Security guide',content:'Rotate tokens.',sourceId:'task-1'},sourceIds:['task-1','invented']})}]}]})}}});assert.equal(r.status,200);assert.equal(request.store,false);assert.match(request.input[0].content,/Use rotating tokens/);assert.match(request.input[0].content,/Draft text/);assert.equal(request.input[1].content,'Rewrite security guide');assert.deepEqual(r.result.sourceIds,['task-1']);assert.equal(JSON.stringify(db),original)});
test('handles provider errors without exposing credentials or upstream details',async()=>{const r=await run({prompt:'Summarize'},{fetchImpl:async()=>({ok:false,status:401})});assert.equal(r.status,502);assert.doesNotMatch(JSON.stringify(r.result),/test-key/)});
test('handles timeout, refusal and incomplete output',async()=>{const timeout=await run({prompt:'Write'},{fetchImpl:async()=>{throw Object.assign(new Error(),{name:'TimeoutError'})}});assert.match(timeout.result.error,/too long/);for(const [data,status] of [[{status:'incomplete'},502],[{output:[{content:[{type:'refusal'}]}]},422]])assert.equal((await run({prompt:'Write'},{fetchImpl:async()=>({ok:true,json:async()=>data})})).status,status)});

test('project AI writing preferences are included in assistant context',async()=>{let context;const dbWithProject={tasks:[{...db.tasks[0],project:'AI H Platform'}],projectSettings:{'AI H Platform':{ai:{style:'Concise',instructions:'Use short paragraphs.'}}}};const result=await run({prompt:'Write a summary'},{read:()=>dbWithProject,fetchImpl:async(_,options)=>{context=JSON.parse(JSON.parse(options.body).input[0].content);return {ok:true,json:async()=>({output:[{content:[{type:'output_text',text:JSON.stringify({answer:'Summary',document:null,sourceIds:[]})}]}]})}}});assert.equal(result.status,200);assert.deepEqual(context.projectWritingPreferences['AI H Platform'],dbWithProject.projectSettings['AI H Platform'].ai)});
