import test from 'node:test';
import assert from 'node:assert/strict';
import {defaultSettings,getSettings,validateSettings,transitionError,registerSettingsRoutes,shouldNotify} from '../server/project-settings.js';
const project='AI H Platform';
const database=()=>({tasks:[{id:'AIH-1',project,assignee:'Ahmed',status:'In Progress',doc:'Not Started',dependencies:[{type:'blockedBy',issueId:'AIH-2'}]},{id:'AIH-2',project,status:'To Do'}],documentTemplates:[{id:'technical',name:'Technical',sections:['Overview']},{id:'custom',name:'Custom',sections:['Summary']}],projectSettings:{}});
function routes(db){const handlers={};registerSettingsRoutes(Object.fromEntries(['get','put','delete'].map(method=>[method,(path,fn)=>handlers[method+' '+path]=fn])),{read:()=>db,save:next=>Object.assign(db,next)});return (method,path,params={},body={})=>{let status=200,data;handlers[method+' '+path]({params,body},{status(code){status=code;return this},json(value){data=value;return this}});return {status,data}}}
test('settings round-trip all seven sections without altering another project',()=>{const db=database(),call=routes(db),config=defaultSettings(project);config.details.name='Platform engineering';config.details.key='ENG';config.members.push({name:'Noor',fullName:'Noor Ali',initials:'NA',role:'Reviewer'});config.issueTypes={names:['Task','Improvement'],defaultType:'Improvement'};config.workflows.defaultStatus='In Progress';config.notifications.taskUpdates=false;config.documentation.defaultTemplate='custom';config.ai.instructions='Use short sentences.';assert.equal(call('put','/api/project-settings/:project',{project},config).status,200);const restored=call('get','/api/project-settings/:project',{project}).data;assert.deepEqual(restored,config);assert.equal(getSettings(db,'Internal Tools').details.name,'Internal Tools');assert.equal(call('get','/api/projects').data[0].details.name,'Platform engineering')});
test('rejects invalid defaults, duplicate keys and removal of assigned members',()=>{for(const change of [c=>c.issueTypes.defaultType='Missing',c=>c.details.key='IT',c=>c.members=c.members.filter(m=>m.name!=='Ahmed'),c=>c.documentation.defaultTemplate='missing',c=>c.notifications.enabled='yes']){const db=database(),config=defaultSettings(project);change(config);assert.throws(()=>validateSettings(config,db,project))}});
test('workflow switches are enforced, including approval and reopening',()=>{const db=database(),task=db.tasks[0];assert.match(transitionError(db,task,'Done'),/Blocked/);const config=defaultSettings(project);db.projectSettings[project]=config;config.workflows.blockIncompleteDependencies=false;assert.match(transitionError(db,task,'Done'),/Approve/);config.documentation.requireApproval=false;assert.equal(transitionError(db,task,'Done'),null);config.workflows.allowReopen=false;assert.match(transitionError(db,{...task,status:'Done'},'To Do'),/disabled/);assert.match(transitionError(db,task,'Unknown'),/Unknown/)});
test('templates can be edited and reordered; active defaults cannot be deleted',()=>{const db=database(),call=routes(db);assert.equal(call('delete','/api/document-templates/:id',{id:'technical'}).status,409);const result=call('put','/api/document-templates/:id',{id:'custom'},{name:'Release',bestFor:'Shipping',sections:['Checks','Overview']});assert.equal(result.status,200);assert.deepEqual(db.documentTemplates[1].sections,['Checks','Overview']);assert.equal(call('delete','/api/document-templates/:id',{id:'custom'}).status,200);assert.equal(db.documentTemplates.length,1)});

test('notification switches only affect the selected project and category',()=>{const db=database();db.projectSettings[project]=defaultSettings(project);db.projectSettings[project].notifications.taskUpdates=false;assert.equal(shouldNotify(db,project,'taskUpdates'),false);assert.equal(shouldNotify(db,project,'documentation'),true);assert.equal(shouldNotify(db,'Internal Tools','taskUpdates'),true);db.projectSettings[project].notifications.enabled=false;assert.equal(shouldNotify(db,project,'documentation'),false)});
