import React, {useEffect, useRef, useState} from 'react';
import {Archive, ArrowDown, ArrowUpDown, ChevronDown, ChevronsLeft, ChevronsRight, FileText, Filter, LockKeyhole, LogIn, MessageSquareText, Mic, MoreHorizontal, Plus, Search, Star, Users, X} from 'lucide-react';
import './docs-workspace.css';
import {DocsAssistant} from './docs-assistant';

type DocTask={id:string,title:string,project?:string,assignee:string,initials:string,labels:string[],doc:string,description:string,documentation?:{generatedAt?:string}};
type Draft={id:string,title:string,content:string,project:string,updated:string,category:string};
type Meta={favorite?:boolean,archived?:boolean,viewed?:string};
function readStored<T,>(key:string,fallback:T):T {try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}}
const templates=[['Project Brief','Clarify project goals','Overview\n\nGoals\n\nScope\n\nSuccess criteria'],['Task Guide','Standardize task details','Purpose\n\nSteps\n\nAcceptance criteria'],['Workflow Wiki','Document your process','Overview\n\nProcess\n\nRoles and responsibilities'],['Workspace Guide','Organize your workspace','Getting started\n\nProjects\n\nTeam practices']];
export function DocsWorkspace<T extends DocTask>({tasks,projects,open}:{tasks:T[],projects:string[],open:(task:T)=>void}){
 const [category,setCategory]=useState('All Docs'),[collapsed,setCollapsed]=useState(false),[query,setQuery]=useState(''),[searching,setSearching]=useState(false),[filter,setFilter]=useState(''),[tag,setTag]=useState(''),[sort,setSort]=useState('updated'),[menu,setMenu]=useState<string|null>(null),[notice,setNotice]=useState('');
 const [drafts,setDrafts]=useState<Draft[]>(()=>readStored('aih-doc-drafts',[])),[metadata,setMetadata]=useState<Record<string,Meta>>(()=>readStored('aih-doc-meta',{})),[editing,setEditing]=useState<Draft|null>(null);
 const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{const dismiss=(event:KeyboardEvent)=>{if(event.key==='Escape'){setMenu(null);setEditing(null)}};window.addEventListener('keydown',dismiss);return()=>window.removeEventListener('keydown',dismiss)},[]);
 const persistDrafts=(next:Draft[])=>{try{localStorage.setItem('aih-doc-drafts',JSON.stringify(next));setDrafts(next);return true}catch{setNotice('Could not save this document. Browser storage may be full.');return false}};
 const mark=(id:string,patch:Meta)=>{const next={...metadata,[id]:{...metadata[id],...patch}};try{localStorage.setItem('aih-doc-meta',JSON.stringify(next));setMetadata(next)}catch{setNotice('Could not save document preferences.')}};
 const create=(title='Untitled Doc',content='',kind='Private')=>{setEditing({id:'doc-'+crypto.randomUUID(),title,content,project:projects[0]||'Workspace',updated:new Date().toISOString(),category:kind});setMenu(null)};
 const entries=[...tasks.filter(t=>t.doc!=='Not Started').map(t=>({id:t.id,title:t.title,project:t.project||'AI H Platform',tags:t.labels,owner:t.assignee,initials:t.initials,updated:t.documentation?.generatedAt||'',category:'Shared with me',task:t,draft:null as Draft|null})),...drafts.map(d=>({id:d.id,title:d.title,project:d.project,tags:d.category==='Meeting Notes'?['meeting']:[],owner:'Ahmed',initials:'AH',updated:d.updated,category:d.category,task:null as T|null,draft:d}))];
 const visible=entries.filter(d=>{const archived=metadata[d.id]?.archived;return (category==='Archived'?archived:!archived)&&(category==='All Docs'||category==='Archived'||category==='My Docs'&&d.owner==='Ahmed'||category==='Shared with me'&&d.category==='Shared with me'||category==='Private'&&d.category==='Private'||category==='Meeting Notes'&&d.category==='Meeting Notes')&&(!filter||d.project===filter)&&(!tag||d.tags.includes(tag))&&(d.title+' '+d.project+' '+d.tags.join(' ')).toLowerCase().includes(query.toLowerCase())}).sort((a,b)=>sort==='name'?a.title.localeCompare(b.title):sort==='viewed'?(metadata[b.id]?.viewed||'').localeCompare(metadata[a.id]?.viewed||''):b.updated.localeCompare(a.updated));
 const launch=(entry:typeof entries[number])=>{mark(entry.id,{viewed:new Date().toISOString()});if(entry.task)open(entry.task);else setEditing(entry.draft)};
 const favorites=entries.filter(d=>metadata[d.id]?.favorite&&!metadata[d.id]?.archived);

 const date=(value?:string)=>value?new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric'}):'–';
 const nav=[['All Docs',FileText],['My Docs',null],['Shared with me',Users],['Private',LockKeyhole],['Meeting Notes',MessageSquareText],['Archived',Archive]] as const;
 return <section className={'docs-hub '+(collapsed?'docs-hub-collapsed':'')} onClick={e=>e.stopPropagation()}>
 <aside className="docs-nav"><div className="docs-nav-heading"><h1>Docs</h1><button aria-label="Collapse Docs sidebar" onClick={()=>setCollapsed(true)}><ChevronsLeft size={16}/></button><button className="docs-light-button" onClick={()=>create()}><Plus size={15}/> Create</button></div><nav>{nav.map(([label,Icon])=><button key={label} className={category===label?'active':''} onClick={()=>{setCategory(label);setMenu(null)}}>{Icon?<Icon size={15}/>:<span className="docs-me">A</span>}<span>{label}</span>{label==='My Docs'&&<small>{entries.filter(d=>d.owner==='Ahmed'&&!metadata[d.id]?.archived).length}</small>}</button>)}</nav><div className="docs-nav-section"><h2>Favorites</h2>{favorites.length?favorites.map(d=><button className="docs-nav-document" key={d.id} onClick={()=>launch(d)}><Star size={14} fill="#ffc83d"/>{d.title}</button>):<div className="docs-nav-empty"><Star size={16} fill="#ffc83d" color="#ffc83d"/><p>Star a Doc to see it here</p></div>}</div></aside>
 <div className="docs-main"><div className="docs-top"><div>{collapsed&&<button onClick={()=>setCollapsed(false)} aria-label="Expand Docs sidebar"><ChevronsRight size={17}/></button>}<b>{category}</b></div><div><button className="docs-outline-button" onClick={()=>file.current?.click()}><LogIn size={14}/> Import</button><div className="docs-menu-anchor"><button className="docs-light-button" onClick={()=>setMenu(menu==='new'?null:'new')}>New Doc <ChevronDown size={13}/></button>{menu==='new'&&<div className="docs-popover"><button onClick={()=>create()}>Blank document</button>{templates.map(([title,,content])=><button key={title} onClick={()=>create(title,content)}>{title}</button>)}<button onClick={()=>create('Meeting Notes','Attendees\n\nAgenda\n\nNotes\n\nAction items','Meeting Notes')}>Meeting Notes</button></div>}</div></div></div>
 <input hidden ref={file} type="file" accept=".txt,.md,text/plain,text/markdown" onChange={async e=>{const selected=e.target.files?.[0];if(!selected)return;try{if(selected.size>2*1024*1024)throw new Error('Choose a text or Markdown file smaller than 2 MB.');create(selected.name.replace(/\.(md|txt)$/i,''),await selected.text())}catch(error){setNotice((error as Error).message)}e.target.value=''}}/>
 <div className="docs-main-content"><DocsAssistant drafts={drafts.filter(d=>!metadata[d.id]?.archived)} sources={entries} onSource={id=>{const entry=entries.find(d=>d.id===id);if(entry)launch(entry)}} onDocument={doc=>{const existing=drafts.find(d=>d.id===doc.sourceId);setEditing(existing?{...existing,title:doc.title,content:doc.content}:{id:'doc-'+crypto.randomUUID(),title:doc.title,content:doc.content,project:entries.find(d=>d.id===doc.sourceId)?.project||projects[0]||'Workspace',updated:new Date().toISOString(),category:'Private'})}}/>
 {notice&&<div className="docs-notice" role="status">{notice}<button aria-label="Dismiss message" onClick={()=>setNotice('')}><X size={14}/></button></div>}
 <div className="docs-library"><div className="docs-toolbar"><div className="docs-menu-anchor"><button className={'docs-pill '+(filter?'selected':'')} onClick={()=>setMenu(menu==='filter'?null:'filter')}><Filter size={14}/> Filters{filter?' · 1':''}</button>{menu==='filter'&&<div className="docs-popover"><b>Location</b>{['',...projects].map(p=><button key={p} className={filter===p?'selected':''} onClick={()=>{setFilter(p);setMenu(null)}}>{p||'All projects'}</button>)}</div>}</div><div className="docs-menu-anchor"><button className="docs-pill" onClick={()=>setMenu(menu==='sort'?null:'sort')}><ArrowUpDown size={13}/> Sort</button>{menu==='sort'&&<div className="docs-popover">{[['updated','Last updated'],['name','Name A–Z'],['viewed','Last viewed']].map(([value,label])=><button key={value} className={sort===value?'selected':''} onClick={()=>{setSort(value);setMenu(null)}}>{label}</button>)}</div>}</div><label className="docs-tags">Tags: <select aria-label="Filter documents by tag" value={tag} onChange={e=>setTag(e.target.value)}><option value="">All</option>{Array.from(new Set(entries.flatMap(d=>d.tags))).map(t=><option key={t}>{t}</option>)}</select></label><div className="docs-search">{searching?<><Search size={14}/><input autoFocus aria-label="Search documents" placeholder="Search docs" value={query} onChange={e=>setQuery(e.target.value)}/><button aria-label="Close search" onClick={()=>{setSearching(false);setQuery('')}}><X size={13}/></button></>:<button onClick={()=>setSearching(true)}><Search size={14}/> Search</button>}</div></div>
 <div className="docs-table-scroll"><table className="docs-library-table"><thead><tr><th>Name</th><th>Location</th><th>Tags</th><th>Date updated</th><th><button onClick={()=>setSort('viewed')}>Date viewed <ArrowDown size={13}/></button></th><th>Sharing</th><th><span className="docs-sr-only">Actions</span></th></tr></thead><tbody>{visible.map(d=><tr key={d.id}><td><button className="docs-document-title" onClick={()=>launch(d)}><FileText size={15}/><span>{d.title}</span></button></td><td><span className="docs-location"><Users size={14}/>{d.project}</span></td><td><span className="docs-table-tags">{d.tags.length?d.tags.join(', '):'–'}</span></td><td>{date(d.updated)}</td><td>{date(metadata[d.id]?.viewed)}</td><td><span className="docs-sharing" title={d.owner}>{d.initials.slice(0,1)}</span></td><td><div className="docs-menu-anchor"><button aria-label={'Actions for '+d.title} onClick={()=>setMenu(menu===d.id?null:d.id)}><MoreHorizontal size={17}/></button>{menu===d.id&&<div className="docs-popover docs-row-menu"><button onClick={()=>{launch(d);setMenu(null)}}>Open document</button><button onClick={()=>{mark(d.id,{favorite:!metadata[d.id]?.favorite});setMenu(null)}}><Star size={13}/>{metadata[d.id]?.favorite?'Remove favorite':'Add to favorites'}</button><button onClick={()=>{mark(d.id,{archived:!metadata[d.id]?.archived});setMenu(null)}}><Archive size={13}/>{metadata[d.id]?.archived?'Restore document':'Archive'}</button></div>}</div></td></tr>)}</tbody></table>{!visible.length&&<div className="docs-table-empty">{query||filter||tag?'No documents match your filters.':'No documents here yet.'}</div>}<div className="docs-table-bottom"/></div>
 </div></div></div>
 {editing&&<div className="docs-edit-backdrop"><form className="docs-edit-dialog" role="dialog" aria-modal="true" aria-label="Document editor" onSubmit={e=>{e.preventDefault();const saved={...editing,updated:new Date().toISOString()};if(persistDrafts([...drafts.filter(d=>d.id!==saved.id),saved]))setEditing(null)}}><div><h2>{drafts.some(d=>d.id===editing.id)?'Edit document':'New document'}</h2><button type="button" aria-label="Close document" onClick={()=>setEditing(null)}><X size={18}/></button></div><label>Name<input autoFocus required value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>Location<select value={editing.project} onChange={e=>setEditing({...editing,project:e.target.value})}>{projects.map(p=><option key={p}>{p}</option>)}</select></label><label>Content<textarea value={editing.content} onChange={e=>setEditing({...editing,content:e.target.value})}/></label><footer><span>Drafts are saved in this browser.</span><button className="docs-light-button" disabled={!editing.title.trim()}>Save document</button></footer></form></div>}
 </section>
}
