import React,{useEffect,useRef,useState} from 'react';
import {ArrowUp,FileText,LoaderCircle,Mic,Plus,Sparkles,X} from 'lucide-react';

type Draft={id:string,title:string,content:string,project:string};
type Result={answer:string,document:{title:string,content:string,sourceId:string|null}|null,sourceIds:string[]};
type Message={role:'user'|'assistant',content:string,result?:Result};
const templates=[['Project Brief','Clarify project goals','Help me write a project brief. Ask me which project and any missing goals first.'],['Task Guide','Standardize task details','Help me create a task guide using our docs. Ask which task I mean.'],['Workflow Wiki','Document your process','Help me write a workflow wiki. Ask which process I want to document.'],['Workspace Guide','Organize your workspace','Create a workspace guide using the available project documents. Clearly mark missing information.']];
export function DocsAssistant({drafts,onDocument,sources,onSource}:{drafts:Draft[],onDocument:(doc:NonNullable<Result['document']>)=>void,sources:{id:string,title:string}[],onSource:(id:string)=>void}){
 const [prompt,setPrompt]=useState(''),[messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[attachment,setAttachment]=useState<{name:string,content:string}|null>(null);
 const input=useRef<HTMLTextAreaElement>(null),file=useRef<HTMLInputElement>(null),controller=useRef<AbortController|null>(null),thread=useRef<HTMLDivElement>(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 useEffect(()=>{thread.current?.scrollTo({top:thread.current.scrollHeight,behavior:'smooth'})},[messages,busy]);
 const ask=async(request=prompt)=>{
  if(!request.trim()||controller.current)return;
  const abort=new AbortController();controller.current=abort;setBusy(true);setError('');
  try{
   const response=await fetch('/api/docs/assistant',{method:'POST',headers:{'Content-Type':'application/json'},signal:abort.signal,body:JSON.stringify({prompt:request,history:messages.slice(-10).map(m=>({role:m.role,content:(m.content+(m.result?.document?'\nProposed document: '+JSON.stringify(m.result.document):'')).slice(0,16000)})),drafts:drafts.slice(0,100),attachment})});
   const data=await response.json().catch(()=>({error:'The assistant is unavailable. Please try again.'}));if(!response.ok)throw new Error(data.error||'Could not get a response.');
   setMessages(current=>[...current,{role:'user',content:request},{role:'assistant',content:data.answer,result:data}]);setPrompt('');
  }catch(e){if((e as Error).name!=='AbortError')setError((e as Error).message)}finally{controller.current=null;setBusy(false)}
 };
 return <><div className="docs-composer-frame"><form className="docs-composer" onSubmit={e=>{e.preventDefault();ask()}}><textarea ref={input} maxLength={8000} disabled={busy} aria-label="Ask AI about your documents" placeholder="Ask AI to create, edit, summarize, or find anything in your docs…" value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();ask()}}}/>{attachment&&<div className="docs-ai-attachment"><FileText size={13}/><span>{attachment.name}</span><button type="button" disabled={busy} onClick={()=>setAttachment(null)} aria-label="Remove attachment"><X size={13}/></button></div>}<div><button type="button" disabled={busy} aria-label="Attach document for AI" onClick={()=>file.current?.click()}><Plus size={17}/></button><span>{busy?<button type="button" className="docs-draft-button" onClick={()=>controller.current?.abort()}>Stop</button>:<><button type="button" aria-label="Dictate document request" onClick={()=>{const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Speech){setError('Voice input is not supported in this browser. Type your request instead.');return}const recognition=new Speech();recognition.onresult=(e:any)=>setPrompt(current=>(current+' '+e.results[0][0].transcript).trim());recognition.onerror=()=>setError('Could not start voice input. Check microphone access.');recognition.start()}}><Mic size={16}/></button><button type="submit" className="docs-ai-send" disabled={!prompt.trim()} aria-label="Send to docs assistant"><ArrowUp size={17}/></button></>}</span></div></form></div>
 <input hidden ref={file} type="file" accept=".txt,.md,text/plain,text/markdown" onChange={async e=>{const selected=e.target.files?.[0];if(!selected)return;try{if(selected.size>120000)throw new Error('Choose a text or Markdown file under 120 KB.');const content=await selected.text();if(content.length>30000)throw new Error('Choose a document with at most 30,000 characters.');setAttachment({name:selected.name,content});setError('')}catch(e){setError((e as Error).message)}e.target.value=''}}/>
 <div className="docs-templates">{templates.map(([title,description,request])=><button disabled={busy} key={title} onClick={()=>{setPrompt(request);ask(request)}}><b>{title}</b><span>{description}</span></button>)}</div>
 {(messages.length>0||busy||error)&&<section className="docs-ai-conversation" aria-label="Document assistant"><header><span><Sparkles size={15}/> Docs assistant</span><button disabled={busy} onClick={()=>{setMessages([]);setError('');setAttachment(null)}}>New conversation</button></header><div ref={thread} className="docs-ai-messages" aria-live="polite">{messages.map((message,index)=><article key={index} className={'docs-ai-message '+message.role}><b>{message.role==='user'?'You':'AI H'}</b><p>{message.content}</p>{message.result?.document&&<div className="docs-ai-proposal"><h3>{message.result.document.title}</h3><pre>{message.result.document.content}</pre><button onClick={()=>onDocument(message.result!.document!)}><FileText size={14}/> Review &amp; save document</button></div>}{!!message.result?.sourceIds.length&&<div className="docs-ai-sources">Sources: {message.result.sourceIds.map(id=><button key={id} onClick={()=>onSource(id)}>{sources.find(s=>s.id===id)?.title||id}</button>)}</div>}</article>)}{busy&&<p className="docs-ai-thinking"><LoaderCircle size={15}/> Working on your docs…</p>}</div>{error&&<div role="alert" className="docs-ai-error">{error}<button disabled={busy||!prompt.trim()} onClick={()=>ask()}>Retry</button></div>}</section>}
 </>
}
